### ISSUE TITLE
Error running wae_mmd

### ISSUE THREAD

**Issue by anuragranj** [schelotto/Wasserstein-AutoEncoders#4]
The following error pops up when running `python wae_mmd.py`. The probable cause is line 227
https://github.com/schelotto/Wasserstein_Autoencoders/blob/master/wae_mmd.py#L227

Why is the loss computed using a vector of 1? Note that it is wae_mmd, not a wae_gan. 

```sh
Traceback (most recent call last):
  File "wae_mmd.py", line 227, in <module>
    recon_loss.backward(one)
  File "pytorch0.4/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "pytorch0.4/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: invalid gradient at index 0 - expected shape [] but got [1]
```

**Comment by GilgameshD** [comment]
I got the same error, looking forward to a solution....

**Comment by schelotto** [comment]
I've fixed that bug.
